import { Time } from "@angular/common";

export class SubmissionSheetEmail
{
    constructor(
     public submission_id:number,
     public submission_date:string,
     public fk_company_id:number,
     public fk_candidate_id:number,
     public fk_user_id:string,
     public candidate_id:number,
     public candidate_name:string,
     public Resume:string,
     public call_date:string,
     public call_time:string,
     public call_status:string,
     public fk_client_job_id:number,
     public interview_date:string,
     public status:string,
     public company_id:number,
     public co_logo:string,
     public co_name:string,
     public class_of_company:string,
     public co_address:string,
     public co_phone_no:string,
     public co_website:string,
     public co_email_id:string,
     public isclient:string,
     public fk_BD_id:string,
     public convert_to_client_date:string,
    // public fk_company_id:number,
     public client_job_id:number,
     public job_type:string,
     public no_of_position:number,
     public shift_time:string,
     public experience:string,
     public salary_package:string,
     public education:string,
     public last_used:string,
     public technical_skill:string,
     public special_skill:string,
     public job_description:string,
     //public fk_BD_id?:string,
    ){}
}